# MySQL
dev.mysql.datasource.username=root
dev.mysql.datasource.password=stephenqhd30.
dev.mysql.datasource.url=jdbc:mysql://localhost:3306/trajectory?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useLocalSessionState=true&useServerPrepStmts=true
# COS
dev.cos.client.accessKey=AKIDBIMOdpx12udEh1AA1whXN4gBiBf5dDuy
dev.cos.client.secretKey=ggJ416Y1X2YQQksupaAbt20oUY8g7gFi
dev.cos.client.region=ap-shanghai
dev.cos.client.bucket=butterfly-1318299170
# Elasticsearch
dev.elasticsearch.uris=http://localhost:9200
dev.elasticsearch.username=elastic
dev.elasticsearch.password=YbG5Wvvm
# Redis
dev.redis.host=localhost
dev.redis.port=6379
dev.redis.database=1
dev.redis.password=
# RabbitMQ
dev.rabbitmq.host=localhost
dev.rabbitmq.port=5672
dev.rabbitmq.username=guest
dev.rabbitmq.password=guest
# Sa-Token
dev.sa-token.jwt-secret-key=Stephenqhd30.
# MinIO
dev.minio.bucket=cloud
dev.minio.endpoint=http://localhost:9000
dev.minio.accessKey=minio
dev.minio.secretKey=stephenqhd30.
# WebSocket
dev.websocket.port=9091
dev.websocket.boss-thread=4
dev.websocket.worker-thread=16
# Mail
dev.mail.host=smtp.163.com
dev.mail.port=465
dev.mail.username=Stephenqhd@163.com
dev.mail.password=DMYk7CGzRvBtk6yu
# Sms
dev.aliyun.sms.accessKeyId=
dev.aliyun.sms.accessKeySecret=
dev.aliyun.sms.regionId=cn-hangzhou
# WX
dev.wx.open.app-id=wx0fecd4ca6f2064fb
dev.wx.open.app-secret=6043fdb2f1f6f4366c347c6a34f5c7bb
dev.wx.qrcode.app-id=your_wx_qrcode_app_id
dev.wx.qrcode.app-secret=your_wx_qrcode_app_secret
dev.wx.qrcode.redirect-uri=http://localhost:8080/api/user/login/wx/callback
# WX MP
dev.wx.mp.token=stephenqiu30
dev.wx.mp.aesKey=6043fdb2f1f64366c347c6a34f5c7bb
dev.wx.mp.appId=wx0fecd4ca6f2064fb
dev.wx.mp.secret=6043fdb2f1f64366c347c6a34f5c7bb
# GitHub OAuth2
dev.github.oauth2.client-id=Ov23lidWX7NDw7BqcSFL
dev.github.oauth2.client-secret=4c6b1938391aa483841b6c597eb7ff5dabcce55c
dev.github.oauth2.redirect-uri=http://localhost:3000/user/login/github/callback
# Aliyun OSS
dev.aliyun.oss.endpoint=oss-cn-hangzhou.aliyuncs.com
dev.aliyun.oss.accessKey=your_aliyun_access_key
dev.aliyun.oss.secretKey=your_aliyun_secret_key
dev.aliyun.oss.bucket=your_aliyun_bucket
# AI
dev.aliyun.dashscope.api-key=sk-25d264d95a9944c3bc9363d7b7a3e9b6
dev.aliyun.dashscope.model-name=qwen-plus
dev.ollama.base-url=http://localhost:11434
dev.ollama.model-name=llama3
# Nacos
dev.nacos.username=nacos
dev.nacos.password=nacos
