# 社交登录配置文件 (Dev/Default)

spring:
  config:
    activate:
      on-profile: default


# GitHub OAuth2 配置
github:
  oauth2:
    client-id: ${dev.github.oauth2.client-id}
    client-secret: ${dev.github.oauth2.client-secret}
    redirect-uri: ${dev.github.oauth2.redirect-uri}
  
