# Domain
prod.server.port=8101
prod.server.servlet.session.cookie.domain=121.36.17.18
# MySQL
prod.mysql.datasource.username=stephen
prod.mysql.datasource.password=Popcornqhd30.
prod.mysql.datasource.url=jdbc:mysql://121.36.17.18:3306/trajectory?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useLocalSessionState=true&useServerPrepStmts=true
# Redis
prod.redis.database=1
prod.redis.host=121.36.17.18
prod.redis.port=6379
prod.redis.password=Popcornqhd30.
# Elasticsearch
prod.elasticsearch.uris=http://152.136.235.18:9200
prod.elasticsearch.username=elastic
prod.elasticsearch.password=Popcornqhd30.
# RabbitMQ
prod.rabbitmq.host=152.136.235.18
prod.rabbitmq.port=5672
prod.rabbitmq.username=rabbitmq
prod.rabbitmq.password=Popcornqhd30.
# Sa-Token
prod.sa-token.jwt-secret-key=Stephenqhd30.
# MinIO
prod.minio.bucket=cloud
prod.minio.endpoint=http://121.36.17.18:9000
prod.minio.accessKey=88tdqYZC0IigvXPac0B6
prod.minio.secretKey=TeZ6D0YYt0bKZ5ZrjBFBKHbct4ynRDcQMYlteEe5
# WebSocket
prod.websocket.port=9091
prod.websocket.boss-thread=4
prod.websocket.worker-thread=16
# Sms
prod.aliyun.sms.accessKeyId=xxx
prod.aliyun.sms.accessKeySecret=xxx
prod.aliyun.sms.regionId=cn-hangzhou
# Aliyun OSS
prod.aliyun.oss.endpoint=oss-cn-hangzhou.aliyuncs.com
prod.aliyun.oss.accessKey=xxx
prod.aliyun.oss.secretKey=xxx
prod.aliyun.oss.bucket=xxx
# WX MP
prod.wx.mp.token=stephenqiu30
prod.wx.mp.aesKey=stephenqiu30stephenqiu30stephenqiu30stephenqiu
prod.wx.mp.appId=wx0fecd4ca6f2064fb
prod.wx.mp.secret=6043fdb2f11f64366c347c6a34f5c7bb
# WX Open
prod.wx.open.app-id=xxx
prod.wx.open.app-secret=xxx
# WX QRCode
prod.wx.qrcode.app-id=xxx
prod.wx.qrcode.app-secret=xxx
prod.wx.qrcode.redirect-uri=xxx
# GitHub OAuth2
prod.github.oauth2.client-id=xxx
prod.github.oauth2.client-secret=xxx
prod.github.oauth2.redirect-uri=xxx
# Mail
prod.mail.host=smtp.163.com
prod.mail.port=465
prod.mail.username=Stephenqhd@163.com
prod.mail.password=DMYk7CGzRvBtk6yu
# AI
prod.aliyun.dashscope.api-key=sk-25d264d95a9944c3bc9363d7b7a3e9b6
prod.aliyun.dashscope.model-name=qwen-plus
prod.ollama.base-url=http://localhost:11434
prod.ollama.model-name=llama3
# Nacos
prod.nacos.username=nacos
prod.nacos.password=nacos
